---
# the configuration file of cmdx - task runner
# https://github.com/suzuki-shunsuke/cmdx
tasks:
- name: test
  short: t
  description: test with aqua-test.yaml
  usage: test with aqua-test.yaml
  script: aqua -c aqua-test.yaml i --test
