---
# the configuration file of cmdx - task runner
# https://github.com/suzuki-shunsuke/cmdx
tasks:
- name: install
  short: i
  description: install all packages
  usage: install all packages
  script: aqua -c aqua-all.yaml i --test
- name: test
  short: t
  description: test with aqua-test.yaml
  usage: test with aqua-test.yaml
  script: aqua -c aqua-test.yaml i --test
- name: exec
  short: x
  description: exec with aqua-test.yaml
  usage: exec with aqua-test.yaml
  script: aqua -c aqua-test.yaml exec -- {{._builtin.args_string}}
- name: generate
  short: g
  description: aqua generate with aqua-all.yaml
  usage: aqua generate with aqua-all.yaml
  script: aqua -c aqua-all.yaml g
- name: release
  short: r
  description: release the new version
  usage: release the new version
  script: |
    git tag "{{.version}}"
    git push origin "{{.version}}"
  args:
  - name: version
    required: true
    validate:
    - regexp: "^v\\d+\\.\\d+.\\d+(-\\d+)?$"
