---
name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  default:
    strategy:
      matrix:
        runs-on: ["ubuntu-latest", "macos-11"]
    runs-on:  ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2

      # Disable cache
      # The cache size is so huge that it takes a long time for `cache ~/.aqua` and `Post cache ~/.aqua`
      # e.g. https://github.com/aquaproj/aqua-registry/runs/4426879327
      #
      # - name: cache ~/.aqua
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.aqua/pkgs
      #       ~/.aqua/registries
      #     key: v5-${{ runner.os }}-${{ hashFiles('registry.yaml') }}-${{ hashFiles('aqua-all.yaml') }}
      #     restore-keys: |
      #       v5-${{ runner.os }}-${{ hashFiles('registry.yaml') }}-
      #       v5-${{ runner.os }}-

      - uses: aquaproj/aqua-installer@main
        with:
          version: v0.8.0 # renovate: depName=aquaproj/aqua
      - run: aqua -c aqua-all.yaml i --test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
